# Generated by Django 4.1.2 on 2022-12-01 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mobileno', models.BigIntegerField()),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mobileno', models.BigIntegerField()),
                ('Lastname', models.CharField(max_length=20)),
                ('Country', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=30)),
                ('State', models.CharField(max_length=30)),
                ('Postcode', models.BigIntegerField()),
                ('userid', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_name', models.CharField(default='', max_length=100)),
                ('offer', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('mobileno', models.BigIntegerField()),
                ('password', models.TextField()),
                ('isblocked', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_image1', models.ImageField(default='', upload_to='img/')),
                ('product_image2', models.ImageField(default='', upload_to='img/')),
                ('product_image3', models.ImageField(default='', upload_to='img/')),
                ('product_image4', models.ImageField(default='', upload_to='img/')),
                ('product_price', models.BigIntegerField()),
                ('product_description', models.TextField()),
                ('subcategory', models.CharField(max_length=200)),
                ('brand', models.CharField(default='', max_length=100)),
                ('stock', models.BigIntegerField(default='0')),
                ('wlist', models.BigIntegerField(default='0')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.category')),
            ],
        ),
        migrations.CreateModel(
            name='Orderdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_prd_name', models.CharField(max_length=300)),
                ('order_prd_price', models.BigIntegerField()),
                ('order_prd_quantity', models.BigIntegerField()),
                ('date', models.DateField()),
                ('user_id', models.IntegerField()),
                ('payment_method', models.CharField(default='', max_length=20)),
                ('status', models.CharField(default='', max_length=20)),
                ('order_prd_image', models.ImageField(default='', upload_to='img/')),
                ('payment_status', models.CharField(default='', max_length=50)),
                ('ord_id', models.CharField(default='', max_length=200)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.adress')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.offer'),
        ),
    ]
