# Generated by Django 4.1.2 on 2022-12-02 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_productinfo_wlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='offer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.coupon'),
        ),
    ]
