# Generated by Django 4.1.2 on 2022-12-02 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_productinfo_offer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('date', models.DateField()),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.coupon')),
            ],
        ),
    ]
