# Generated by Django 4.1.2 on 2022-12-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_coupon_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='profile_pic',
            field=models.ImageField(default='', upload_to='img/'),
        ),
    ]
